var GOOGLE_CLIENT_ID = "98296414098.apps.googleusercontent.com";
var GOOGLE_CLIENT_SECRET = "jzMFeA4lTbnT6eQOVCwZBS6u";

exports.GOOGLE_CLIENT_ID = GOOGLE_CLIENT_ID;
exports.GOOGLE_CLIENT_SECRET = GOOGLE_CLIENT_SECRET;